# Generated by Django 2.0.2 on 2018-02-26 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='isbn',
            field=models.CharField(help_text='15 Character <a href="https://www.isbn-international.org/content/what-isbn">ISBN number</a>', max_length=15, verbose_name='ISBN'),
        ),
        migrations.AlterField(
            model_name='book',
            name='summary',
            field=models.TextField(help_text='Кітаптың сипаттамасын еңгізіңіз', max_length=1000),
        ),
        migrations.AlterField(
            model_name='genre',
            name='name',
            field=models.CharField(help_text='Санатты енгізіңіз', max_length=200),
        ),
    ]
